const workouts = [
  {
    user_name: "Matt Campbell",
    workout_num: 1,
    weight: 160,
    user_reps: 5,
    user_sets: 3,
    id: 1,
    name: "Barbell Bench Press",
    description: "The Barbell Bench Press is an upper-body weight training exercise where you push a weight upwards while lying on a weight training bench. The exercise uses the pectoralis major, the anterior deltoids, and the triceps, among other stabilizing muscles.",
    thumbnail: "https://www.burnthefatinnercircle.com/members/images/1691.jpg",
    video: "https://www.youtube.com/embed/CjHIKDQ4RQo",
    reps: "8",
    sets: "5",
    muscle_group_id: 1
    },
    {
    user_name: "Matt Campbell",
    workout_num: 1,
    weight: 130,
    user_reps: 6,
    user_sets: 3,
    id: 2,
    name: "Incline Dumbell Bench Press",
    description: "An incline press elevates the shoulders and lowers the pelvis as if reclining in a chair. Press weights overhead and conctract by bringing hands towards shoulders. This variation of the bench press emphasizes anterior deltoids with little emphasis at the upper (clavicular) head of the pectoralis major.",
    thumbnail: "https://www.burnthefatinnercircle.com/members/images/1749.jpg",
    video: "https://www.youtube.com/embed/oZVCBM9f8Eo",
    reps: "8",
    sets: "4",
    muscle_group_id: 1
    }]

const workoutsLong = [
  {
    user_name: "Matt Campbell",
    workout_num: 1,
    weight: 160,
    user_reps: 5,
    user_sets: 3,
    id: 1,
    name: "Barbell Bench Press",
    description: "The Barbell Bench Press is an upper-body weight training exercise where you push a weight upwards while lying on a weight training bench. The exercise uses the pectoralis major, the anterior deltoids, and the triceps, among other stabilizing muscles.",
    thumbnail: "https://www.burnthefatinnercircle.com/members/images/1691.jpg",
    video: "https://www.youtube.com/embed/CjHIKDQ4RQo",
    reps: "8",
    sets: "5",
    muscle_group_id: 1
  },
  {
    user_name: "Matt Campbell",
    workout_num: 1,
    weight: 130,
    user_reps: 6,
    user_sets: 3,
    id: 2,
    name: "Incline Dumbell Bench Press",
    description: "An incline press elevates the shoulders and lowers the pelvis as if reclining in a chair. Press weights overhead and conctract by bringing hands towards shoulders. This variation of the bench press emphasizes anterior deltoids with little emphasis at the upper (clavicular) head of the pectoralis major.",
    thumbnail: "https://www.burnthefatinnercircle.com/members/images/1749.jpg",
    video: "https://www.youtube.com/embed/oZVCBM9f8Eo",
    reps: "8",
    sets: "4",
    muscle_group_id: 1
  },
  {
    user_name: "Matt Campbell",
    workout_num: 1,
    weight: 80,
    user_reps: 12,
    user_sets: 4,
    id: 3,
    name: "Cable Crossover/Cable Fly",
    description: "The cable fly or cable crossover is a great isolation exercise that can help to build chest mass. The cables provide resistance throughout the entire movement, making it slightly more challenging than a dumbbell fly.",
    thumbnail: "https://sporium.net/wp-content/uploads/2020/11/Cable-Crossover-nereyi-calistirir.jpg",
    video: "https://www.youtube.com/embed/QcTcWpkn_bw",
    reps: "12",
    sets: "3",
    muscle_group_id: 1
  },
  {
    user_name: "Matt Campbell",
    workout_num: 1,
    weight: 40,
    user_reps: 12,
    user_sets: 3,
    id: 16,
    name: "Low Cable Crossover",
    description: "Cables exercises provide constant tension on the muscles, making them an effective way to build strength. The Low Cable Crossover is a great chest isolation exercise which uses cables, making it a great exercise to include in your training when you want to build up strength and size in your chest.",
    thumbnail: "https://fitexercises.com/images/Low-Cable-Crossover-1.png",
    video: "https://www.youtube.com/embed/wnFEC_34Bls",
    reps: "7",
    sets: "4",
    muscle_group_id: 1
  },
  {
    user_name: "Matt Campbell",
    workout_num: 1,
    weight: 0,
    user_reps: 20,
    user_sets: 3,
    id: 17,
    name: "Wide Grip Push Up",
    description: "Wide grip push ups have a wider hand placement than standard push ups, which places more emphasis on the chest.",
    thumbnail: "https://www.mybodycreator.com/content/files/2020/09/22/482_M.png",
    video: "https://www.youtube.com/embed/UFa702F5WnY",
    reps: "20",
    sets: "3",
    muscle_group_id: 1
  }
];

const userWorkouts = [
  {
  user_name: "Matt Campbell",
  workout_num: 1,
  weight: 160,
  user_reps: 5,
  user_sets: 3,
  id: 1,
  name: "Barbell Bench Press",
  description: "The Barbell Bench Press is an upper-body weight training exercise where you push a weight upwards while lying on a weight training bench. The exercise uses the pectoralis major, the anterior deltoids, and the triceps, among other stabilizing muscles.",
  thumbnail: "https://www.burnthefatinnercircle.com/members/images/1691.jpg",
  video: "https://www.youtube.com/embed/CjHIKDQ4RQo",
  reps: "8",
  sets: "5",
  muscle_group_id: 1
  },
  {
  user_name: "Matt Campbell",
  workout_num: 1,
  weight: 130,
  user_reps: 6,
  user_sets: 3,
  id: 2,
  name: "Incline Dumbell Bench Press",
  description: "An incline press elevates the shoulders and lowers the pelvis as if reclining in a chair. Press weights overhead and conctract by bringing hands towards shoulders. This variation of the bench press emphasizes anterior deltoids with little emphasis at the upper (clavicular) head of the pectoralis major.",
  thumbnail: "https://www.burnthefatinnercircle.com/members/images/1749.jpg",
  video: "https://www.youtube.com/embed/oZVCBM9f8Eo",
  reps: "8",
  sets: "4",
  muscle_group_id: 1
  },
  {
  user_name: "Matt Campbell",
  workout_num: 1,
  weight: 80,
  user_reps: 12,
  user_sets: 4,
  id: 3,
  name: "Cable Crossover/Cable Fly",
  description: "The cable fly or cable crossover is a great isolation exercise that can help to build chest mass. The cables provide resistance throughout the entire movement, making it slightly more challenging than a dumbbell fly.",
  thumbnail: "https://sporium.net/wp-content/uploads/2020/11/Cable-Crossover-nereyi-calistirir.jpg",
  video: "https://www.youtube.com/embed/QcTcWpkn_bw",
  reps: "12",
  sets: "3",
  muscle_group_id: 1
  },
  {
  user_name: "Matt Campbell",
  workout_num: 1,
  weight: 40,
  user_reps: 12,
  user_sets: 3,
  id: 16,
  name: "Low Cable Crossover",
  description: "Cables exercises provide constant tension on the muscles, making them an effective way to build strength. The Low Cable Crossover is a great chest isolation exercise which uses cables, making it a great exercise to include in your training when you want to build up strength and size in your chest.",
  thumbnail: "https://fitexercises.com/images/Low-Cable-Crossover-1.png",
  video: "https://www.youtube.com/embed/wnFEC_34Bls",
  reps: "7",
  sets: "4",
  muscle_group_id: 1
  },
  {
  user_name: "Matt Campbell",
  workout_num: 1,
  weight: 0,
  user_reps: 20,
  user_sets: 3,
  id: 17,
  name: "Wide Grip Push Up",
  description: "Wide grip push ups have a wider hand placement than standard push ups, which places more emphasis on the chest.",
  thumbnail: "https://www.mybodycreator.com/content/files/2020/09/22/482_M.png",
  video: "https://www.youtube.com/embed/UFa702F5WnY",
  reps: "20",
  sets: "3",
  muscle_group_id: 1
  },
  {
  user_name: "Matt Campbell",
  workout_num: 4,
  weight: 200,
  user_reps: 5,
  user_sets: 3,
  id: 10,
  name: "Barbell Deadlift",
  description: "The deadlift is a weight training exercise in which a loaded barbell or bar is lifted off the ground to the level of the hips, torso perpendicular to the floor, before being placed back on the ground",
  thumbnail: "https://thumbs.dreamstime.com/b/exercising-deadlifts-barbell-bodybuilding-target-muscles-marked-red-initial-final-steps-43605848.jpg",
  video: "https://www.youtube.com/embed/GxsLrTzyGUU",
  reps: "6",
  sets: "5",
  muscle_group_id: 3
  },
  {
  user_name: "Matt Campbell",
  workout_num: 4,
  weight: 100,
  user_reps: 12,
  user_sets: 3,
  id: 11,
  name: "Wide Grip Pulldown",
  description: "The wide grip lat pulldown mainly works the lats, but the biceps, forearms, and upper back.",
  thumbnail: "https://cdn.shopify.com/s/files/1/0269/5551/3900/files/Wide-Grip-Pulldown_91fcba9b-47a2-4185-b093-aa542c81c55c_600x600.png?v=1612138105",
  video: "https://www.youtube.com/embed/7JnP8dFbS14",
  reps: "12",
  sets: "4",
  muscle_group_id: 3
  },
  {
  user_name: "Matt Campbell",
  workout_num: 4,
  weight: 140,
  user_reps: 10,
  user_sets: 4,
  id: 12,
  name: "Seated Cable Row",
  description: "This exercise works the upper, middle, and lower back",
  thumbnail: "https://cdn.shopify.com/s/files/1/0269/5551/3900/files/Seated-Cable-Row_9470fa48-f0d1-40b1-a980-caee9e6f2e53_600x600.png?v=1612138127",
  video: "https://www.youtube.com/embed/lJoozxC0Rns",
  reps: "12",
  sets: "3",
  muscle_group_id: 3
  },
  {
  user_name: "Matt Campbell",
  workout_num: 4,
  weight: 40,
  user_reps: 12,
  user_sets: 3,
  id: 20,
  name: "Bent Over Row",
  description: "The dumbbell bent over row is a staple back exercise which targets almost all of the muscles in the upper and middle back.",
  thumbnail: "https://cdn.shopify.com/s/files/1/0269/5551/3900/files/Dumbbell-Bent-Over-Rows_600x600.png?v=1619977463",
  video: "https://www.youtube.com/embed/6gvmcqr226U",
  reps: "10",
  sets: "4",
  muscle_group_id: 3
  },
  {
  user_name: "Matt Campbell",
  workout_num: 4,
  weight: 20,
  user_reps: 20,
  user_sets: 3,
  id: 21,
  name: "Assisted Pull Ups",
  description: "An assisted pull-up is a bodyweight exercise that helps you work your way up to performing a full unassisted pull-up, an advanced upper-body exercise. Assisted pull-ups are an excellent strength-training exercise that targets your chest, shoulders, arms, abdominal, and back muscles",
  thumbnail: "https://qph.fs.quoracdn.net/main-qimg-229bbca94f2902f40278d5e8c64e92ee-lq",
  video: "https://www.youtube.com/embed/wFj808u2HWU",
  reps: "8",
  sets: "4",
  muscle_group_id: 3
  }
  ];

module.exports = {workouts, workoutsLong, userWorkouts}